# Created by Jekyll Writer
title: perry's blog
email: li3741@qq.com
description: Write an awesome description for your new site here
baseurl: /blog
url: ''
permalink: '/:year/:month/:day/:title/'
twitter_username: jekyllwriter
github_username: jekyllwriter
markdown: kramdown
