# Created by Jekyll Writer
title: perry's blog
email: li3741@qq.com
description: will you be afreelancer?
baseurl: /blog
url: /blog/
permalink: '/:year/:month/:day/:title/'
twitter_username: li3741
github_username: li3741
markdown: kramdown
